# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_cenra.ui'
#
# Created: Fri Aug 29 15:27:40 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_cenra(object):
    def setupUi(self, cenra):
        cenra.setObjectName(_fromUtf8("cenra"))
        cenra.resize(533, 565)
        self.buttonBox = QtGui.QDialogButtonBox(cenra)
        self.buttonBox.setGeometry(QtCore.QRect(350, 530, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.Titre = QtGui.QLabel(cenra)
        self.Titre.setGeometry(QtCore.QRect(40, 10, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Titre.setFont(font)
        self.Titre.setObjectName(_fromUtf8("Titre"))
        self.groupBox = QtGui.QGroupBox(cenra)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 511, 121))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 126, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_dept = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_dept.setFont(font)
        self.label_dept.setObjectName(_fromUtf8("label_dept"))
        self.horizontalLayout.addWidget(self.label_dept)
        self.dept = QtGui.QComboBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dept.setFont(font)
        self.dept.setObjectName(_fromUtf8("dept"))
        self.dept.addItem(_fromUtf8(""))
        self.dept.setItemText(0, _fromUtf8(""))
        self.dept.addItem(_fromUtf8(""))
        self.dept.addItem(_fromUtf8(""))
        self.dept.addItem(_fromUtf8(""))
        self.dept.addItem(_fromUtf8(""))
        self.dept.addItem(_fromUtf8(""))
        self.dept.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.dept)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 50, 481, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_nom = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_nom.setFont(font)
        self.label_nom.setObjectName(_fromUtf8("label_nom"))
        self.horizontalLayout_2.addWidget(self.label_nom)
        self.nom = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nom.setFont(font)
        self.nom.setObjectName(_fromUtf8("nom"))
        self.horizontalLayout_2.addWidget(self.nom)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 80, 479, 31))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.horizontalLayoutWidget_6 = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(339, 20, 161, 31))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.at = QtGui.QCheckBox(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.at.setFont(font)
        self.at.setObjectName(_fromUtf8("at"))
        self.horizontalLayout_6.addWidget(self.at)
        self.groupBox_2 = QtGui.QGroupBox(cenra)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 190, 511, 241))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 162, 141))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.couche_habitat = QtGui.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.couche_habitat.setFont(font)
        self.couche_habitat.setObjectName(_fromUtf8("couche_habitat"))
        self.gridLayout.addWidget(self.couche_habitat, 1, 0, 1, 1)
        self.couche_contour = QtGui.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.couche_contour.setFont(font)
        self.couche_contour.setObjectName(_fromUtf8("couche_contour"))
        self.gridLayout.addWidget(self.couche_contour, 0, 0, 1, 1)
        self.annee_4 = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.annee_4.setFont(font)
        self.annee_4.setAlignment(QtCore.Qt.AlignCenter)
        self.annee_4.setObjectName(_fromUtf8("annee_4"))
        self.gridLayout.addWidget(self.annee_4, 4, 1, 1, 1)
        self.couche_travaux_prevus = QtGui.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.couche_travaux_prevus.setFont(font)
        self.couche_travaux_prevus.setObjectName(_fromUtf8("couche_travaux_prevus"))
        self.gridLayout.addWidget(self.couche_travaux_prevus, 3, 0, 1, 1)
        self.annee_5 = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.annee_5.setFont(font)
        self.annee_5.setAlignment(QtCore.Qt.AlignCenter)
        self.annee_5.setObjectName(_fromUtf8("annee_5"))
        self.gridLayout.addWidget(self.annee_5, 3, 1, 1, 1)
        self.couche_vierge = QtGui.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.couche_vierge.setFont(font)
        self.couche_vierge.setObjectName(_fromUtf8("couche_vierge"))
        self.gridLayout.addWidget(self.couche_vierge, 4, 0, 1, 1)
        self.couche_travaux_realises = QtGui.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.couche_travaux_realises.setFont(font)
        self.couche_travaux_realises.setObjectName(_fromUtf8("couche_travaux_realises"))
        self.gridLayout.addWidget(self.couche_travaux_realises, 2, 0, 1, 1)
        self.annee_1 = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.annee_1.setFont(font)
        self.annee_1.setAlignment(QtCore.Qt.AlignCenter)
        self.annee_1.setObjectName(_fromUtf8("annee_1"))
        self.gridLayout.addWidget(self.annee_1, 0, 1, 1, 1)
        self.annee_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.annee_3.setFont(font)
        self.annee_3.setAlignment(QtCore.Qt.AlignCenter)
        self.annee_3.setObjectName(_fromUtf8("annee_3"))
        self.gridLayout.addWidget(self.annee_3, 2, 1, 1, 1)
        self.annee_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.annee_2.setFont(font)
        self.annee_2.setAlignment(QtCore.Qt.AlignCenter)
        self.annee_2.setObjectName(_fromUtf8("annee_2"))
        self.gridLayout.addWidget(self.annee_2, 1, 1, 1, 1)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(50, 170, 451, 31))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_nom_couche_vierge = QtGui.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_nom_couche_vierge.setFont(font)
        self.label_nom_couche_vierge.setObjectName(_fromUtf8("label_nom_couche_vierge"))
        self.horizontalLayout_4.addWidget(self.label_nom_couche_vierge)
        self.nom_couche_vierge = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nom_couche_vierge.setFont(font)
        self.nom_couche_vierge.setObjectName(_fromUtf8("nom_couche_vierge"))
        self.horizontalLayout_4.addWidget(self.nom_couche_vierge)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(50, 200, 341, 31))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_geom_couche_vierge = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_geom_couche_vierge.setMinimumSize(QtCore.QSize(152, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_geom_couche_vierge.setFont(font)
        self.label_geom_couche_vierge.setObjectName(_fromUtf8("label_geom_couche_vierge"))
        self.horizontalLayout_5.addWidget(self.label_geom_couche_vierge)
        self.couche_vierge_point = QtGui.QRadioButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.couche_vierge_point.setFont(font)
        self.couche_vierge_point.setObjectName(_fromUtf8("couche_vierge_point"))
        self.horizontalLayout_5.addWidget(self.couche_vierge_point)
        self.couche_vierge_ligne = QtGui.QRadioButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.couche_vierge_ligne.setFont(font)
        self.couche_vierge_ligne.setObjectName(_fromUtf8("couche_vierge_ligne"))
        self.horizontalLayout_5.addWidget(self.couche_vierge_ligne)
        self.couche_vierge_polygone = QtGui.QRadioButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.couche_vierge_polygone.setFont(font)
        self.couche_vierge_polygone.setObjectName(_fromUtf8("couche_vierge_polygone"))
        self.horizontalLayout_5.addWidget(self.couche_vierge_polygone)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(320, 60, 60, 29))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(240, 90, 221, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(240, 110, 221, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.groupBox_3 = QtGui.QGroupBox(cenra)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 440, 511, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 471, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(120, 50, 141, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(270, 40, 41, 41))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setTextFormat(QtCore.Qt.PlainText)
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8("page_ajout.png")))
        self.label_8.setObjectName(_fromUtf8("label_8"))

        self.retranslateUi(cenra)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), cenra.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), cenra.reject)
        QtCore.QMetaObject.connectSlotsByName(cenra)

    def retranslateUi(self, cenra):
        cenra.setWindowTitle(_translate("cenra", "Nouveau Projet Cartographique", None))
        self.Titre.setText(_translate("cenra", "Création d\'un nouveau dossier cartographique", None))
        self.groupBox.setTitle(_translate("cenra", "Généralités", None))
        self.label_dept.setText(_translate("cenra", "Département :", None))
        self.dept.setItemText(1, _translate("cenra", "01", None))
        self.dept.setItemText(2, _translate("cenra", "07", None))
        self.dept.setItemText(3, _translate("cenra", "26", None))
        self.dept.setItemText(4, _translate("cenra", "42", None))
        self.dept.setItemText(5, _translate("cenra", "69", None))
        self.dept.setItemText(6, _translate("cenra", "form", None))
        self.label_nom.setText(_translate("cenra", "Nom du dossier :", None))
        self.label_2.setText(_translate("cenra", "Attention :", None))
        self.label.setText(_translate("cenra", "Le nom du dossier ne doit comporter ni caractères spéciaux, ni espaces, ni majuscules", None))
        self.at.setText(_translate("cenra", "Animation Territoriale", None))
        self.groupBox_2.setTitle(_translate("cenra", "Liste des couches à ajouter lors de la création", None))
        self.couche_habitat.setText(_translate("cenra", "Habitat", None))
        self.couche_contour.setText(_translate("cenra", "Contour", None))
        self.annee_4.setText(_translate("cenra", "aaaa", None))
        self.couche_travaux_prevus.setText(_translate("cenra", "Travaux Prévus", None))
        self.annee_5.setText(_translate("cenra", "aaaa", None))
        self.couche_vierge.setText(_translate("cenra", "Vierge", None))
        self.couche_travaux_realises.setText(_translate("cenra", "Travaux Réalisés", None))
        self.annee_1.setText(_translate("cenra", "aaaa", None))
        self.annee_3.setText(_translate("cenra", "aaaa", None))
        self.annee_2.setText(_translate("cenra", "aaaa", None))
        self.label_nom_couche_vierge.setText(_translate("cenra", "- Nom de la couche vierge :", None))
        self.label_geom_couche_vierge.setText(_translate("cenra", "- Geométrie de la couche vierge :", None))
        self.couche_vierge_point.setText(_translate("cenra", "Point", None))
        self.couche_vierge_ligne.setText(_translate("cenra", "Ligne", None))
        self.couche_vierge_polygone.setText(_translate("cenra", "Polygone", None))
        self.label_3.setText(_translate("cenra", "Attention :", None))
        self.label_4.setText(_translate("cenra", "Le nom de la couche vierge ne doit comporter", None))
        self.label_5.setText(_translate("cenra", "ni caractères spéciaux, ni espaces", None))
        self.groupBox_3.setTitle(_translate("cenra", "Note", None))
        self.label_6.setText(_translate("cenra", "Vous pourez à tous moment ajouter de nouvelles couches à votre dossier, à l\'aide de l\'outil :", None))
        self.label_7.setText(_translate("cenra", "Ajout de nouvelles couches", None))

