# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_table_postgis.ui'
#
# Created: Thu Mar 27 16:17:32 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_table_postgis(object):
    def setupUi(self, table_postgis):
        table_postgis.setObjectName(_fromUtf8("table_postgis"))
        table_postgis.resize(532, 364)
        self.buttonBox = QtGui.QDialogButtonBox(table_postgis)
        self.buttonBox.setGeometry(QtCore.QRect(360, 330, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.Titre = QtGui.QLabel(table_postgis)
        self.Titre.setGeometry(QtCore.QRect(170, 0, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Titre.setFont(font)
        self.Titre.setObjectName(_fromUtf8("Titre"))
        self.groupBox_2 = QtGui.QGroupBox(table_postgis)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 511, 241))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 162, 141))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.couche_habitat = QtGui.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.couche_habitat.setFont(font)
        self.couche_habitat.setObjectName(_fromUtf8("couche_habitat"))
        self.gridLayout.addWidget(self.couche_habitat, 1, 0, 1, 1)
        self.couche_contour = QtGui.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.couche_contour.setFont(font)
        self.couche_contour.setObjectName(_fromUtf8("couche_contour"))
        self.gridLayout.addWidget(self.couche_contour, 0, 0, 1, 1)
        self.annee_4 = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.annee_4.setFont(font)
        self.annee_4.setAlignment(QtCore.Qt.AlignCenter)
        self.annee_4.setObjectName(_fromUtf8("annee_4"))
        self.gridLayout.addWidget(self.annee_4, 4, 1, 1, 1)
        self.couche_travaux_prevus = QtGui.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.couche_travaux_prevus.setFont(font)
        self.couche_travaux_prevus.setObjectName(_fromUtf8("couche_travaux_prevus"))
        self.gridLayout.addWidget(self.couche_travaux_prevus, 3, 0, 1, 1)
        self.annee_5 = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.annee_5.setFont(font)
        self.annee_5.setAlignment(QtCore.Qt.AlignCenter)
        self.annee_5.setObjectName(_fromUtf8("annee_5"))
        self.gridLayout.addWidget(self.annee_5, 3, 1, 1, 1)
        self.couche_vierge = QtGui.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.couche_vierge.setFont(font)
        self.couche_vierge.setObjectName(_fromUtf8("couche_vierge"))
        self.gridLayout.addWidget(self.couche_vierge, 4, 0, 1, 1)
        self.couche_travaux_realises = QtGui.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.couche_travaux_realises.setFont(font)
        self.couche_travaux_realises.setObjectName(_fromUtf8("couche_travaux_realises"))
        self.gridLayout.addWidget(self.couche_travaux_realises, 2, 0, 1, 1)
        self.annee_1 = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.annee_1.setFont(font)
        self.annee_1.setAlignment(QtCore.Qt.AlignCenter)
        self.annee_1.setObjectName(_fromUtf8("annee_1"))
        self.gridLayout.addWidget(self.annee_1, 0, 1, 1, 1)
        self.annee_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.annee_3.setFont(font)
        self.annee_3.setAlignment(QtCore.Qt.AlignCenter)
        self.annee_3.setObjectName(_fromUtf8("annee_3"))
        self.gridLayout.addWidget(self.annee_3, 2, 1, 1, 1)
        self.annee_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.annee_2.setFont(font)
        self.annee_2.setAlignment(QtCore.Qt.AlignCenter)
        self.annee_2.setObjectName(_fromUtf8("annee_2"))
        self.gridLayout.addWidget(self.annee_2, 1, 1, 1, 1)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(50, 170, 451, 31))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_nom_couche_vierge = QtGui.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_nom_couche_vierge.setFont(font)
        self.label_nom_couche_vierge.setObjectName(_fromUtf8("label_nom_couche_vierge"))
        self.horizontalLayout_4.addWidget(self.label_nom_couche_vierge)
        self.nom_couche_vierge = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nom_couche_vierge.setFont(font)
        self.nom_couche_vierge.setObjectName(_fromUtf8("nom_couche_vierge"))
        self.horizontalLayout_4.addWidget(self.nom_couche_vierge)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(50, 200, 341, 31))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_geom_couche_vierge = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_geom_couche_vierge.setMinimumSize(QtCore.QSize(152, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_geom_couche_vierge.setFont(font)
        self.label_geom_couche_vierge.setObjectName(_fromUtf8("label_geom_couche_vierge"))
        self.horizontalLayout_5.addWidget(self.label_geom_couche_vierge)
        self.couche_vierge_point = QtGui.QRadioButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.couche_vierge_point.setFont(font)
        self.couche_vierge_point.setObjectName(_fromUtf8("couche_vierge_point"))
        self.horizontalLayout_5.addWidget(self.couche_vierge_point)
        self.couche_vierge_ligne = QtGui.QRadioButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.couche_vierge_ligne.setFont(font)
        self.couche_vierge_ligne.setObjectName(_fromUtf8("couche_vierge_ligne"))
        self.horizontalLayout_5.addWidget(self.couche_vierge_ligne)
        self.couche_vierge_polygone = QtGui.QRadioButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.couche_vierge_polygone.setFont(font)
        self.couche_vierge_polygone.setObjectName(_fromUtf8("couche_vierge_polygone"))
        self.horizontalLayout_5.addWidget(self.couche_vierge_polygone)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(320, 60, 60, 29))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(240, 90, 221, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(240, 110, 221, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayoutWidget = QtGui.QWidget(table_postgis)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 511, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.schema_label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.schema_label.setMaximumSize(QtCore.QSize(75, 16777215))
        self.schema_label.setObjectName(_fromUtf8("schema_label"))
        self.horizontalLayout.addWidget(self.schema_label)
        self.schema = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.schema.setObjectName(_fromUtf8("schema"))
        self.horizontalLayout.addWidget(self.schema)

        self.retranslateUi(table_postgis)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), table_postgis.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), table_postgis.reject)
        QtCore.QMetaObject.connectSlotsByName(table_postgis)

    def retranslateUi(self, table_postgis):
        table_postgis.setWindowTitle(_translate("table_postgis", "Ajout d\'une table", None))
        self.Titre.setText(_translate("table_postgis", "Création de table", None))
        self.groupBox_2.setTitle(_translate("table_postgis", "Liste des couches à ajouter dans le projet", None))
        self.couche_habitat.setText(_translate("table_postgis", "Habitat", None))
        self.couche_contour.setText(_translate("table_postgis", "Contour", None))
        self.annee_4.setText(_translate("table_postgis", "aaaa", None))
        self.couche_travaux_prevus.setText(_translate("table_postgis", "Travaux Prévus", None))
        self.annee_5.setText(_translate("table_postgis", "aaaa", None))
        self.couche_vierge.setText(_translate("table_postgis", "Vierge", None))
        self.couche_travaux_realises.setText(_translate("table_postgis", "Travaux Réalisés", None))
        self.annee_1.setText(_translate("table_postgis", "aaaa", None))
        self.annee_3.setText(_translate("table_postgis", "aaaa", None))
        self.annee_2.setText(_translate("table_postgis", "aaaa", None))
        self.label_nom_couche_vierge.setText(_translate("table_postgis", "- Nom de la couche vierge :", None))
        self.label_geom_couche_vierge.setText(_translate("table_postgis", "- Geométrie de la couche vierge :", None))
        self.couche_vierge_point.setText(_translate("table_postgis", "Point", None))
        self.couche_vierge_ligne.setText(_translate("table_postgis", "Ligne", None))
        self.couche_vierge_polygone.setText(_translate("table_postgis", "Polygone", None))
        self.label_3.setText(_translate("table_postgis", "Attention :", None))
        self.label_4.setText(_translate("table_postgis", "Le nom de la couche vierge ne doit comporter", None))
        self.label_5.setText(_translate("table_postgis", "ni caractères spéciaux, ni espaces", None))
        self.schema_label.setText(_translate("table_postgis", "Nom du projet :", None))

